module.exports = {
    consequence: '../models/consequenceModel',
    effort: '../models/effortModel',
    reason: '../models/reasonModel',
    repayment: '../models/repaymentModel',
    event: '../models/eventModel',
    user: '../models/userModel',
    businessLine_dict: '../models/dictModels/businessLine',
    client_dict: '../models/dictModels/client',
    consequenceType_dict: '../models/dictModels/consequenceType',
    cpr_dict: '../models/dictModels/cpr',
    currency_dict: '../models/dictModels/currency',
    defenceLine_dict: '../models/dictModels/defenceLine',
    functionalBlock_dict: '../models/dictModels/functBlock',
    OtherRiskModel_ConsequenceModel: '../models/dictModels/orgStructure',
    otherRiskConn_dict: '../models/dictModels/otherRisk',
    process_dict: '../models/dictModels/process',
    reasonType_dict: '../models/dictModels/reasonType',
    repaymentType_dict: '../models/dictModels/repaymentType',
    repaymentTypeGroup_dict: '../models/dictModels/repaymentTypeGroup',
    researcher_dict: '../models/dictModels/researcher',
    riskType_dict: '../models/dictModels/riskType',
    sourceType_dict: '../models/dictModels/sourceType',
    status_dict: '../models/dictModels/status',
    orgStructure_dict: '../models/dictModels/orgStructure'
};